// Define tokens para la inyección de dependencias
export const REPOSITORY_TOKENS = {
  USER_REPOSITORY: 'USER_REPOSITORY',
  ORDER_REPOSITORY: 'ORDER_REPOSITORY',
  INSTRUMENT_REPOSITORY: 'INSTRUMENT_REPOSITORY',
  MARKET_DATA_REPOSITORY: 'MARKET_DATA_REPOSITORY',
  PORTFOLIO_REPOSITORY: 'PORTFOLIO_REPOSITORY',
};

export const DI_TOKENS = {
  USER_REPOSITORY: 'USER_REPOSITORY',
  ORDER_REPOSITORY: 'ORDER_REPOSITORY',
  INSTRUMENT_REPOSITORY: 'INSTRUMENT_REPOSITORY',
  MARKET_DATA_REPOSITORY: 'MARKET_DATA_REPOSITORY',
  PORTFOLIO_REPOSITORY: 'PORTFOLIO_REPOSITORY',
};
